# This is a basic workflow to help you get started with Actions

name: Test @notesnook-importer/enex

# Controls when the action will run.
on:
  # Triggers the workflow on push events or manually
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "packages/enex/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: |
          npm i
          npm run test:enex
